services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${SPRING_DATASOURCE_DB_NAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
    ports:
      - 5432:5432
    networks:
      - app-net
  currency_app:
    depends_on:
      - database
    image: currency_app:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${SPRING_DATASOURCE_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - 8080:8080
    networks:
      - app-net

networks:
  app-net:
    driver: bridge