spring:
  application:
    name: currency_app
  datasource:
    url: jdbc:postgresql://localhost:5432/${SPRING_DATASOURCE_DB_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.2
      base-url: "https://api.openai.com/v1/chat/completions"
  mail:
    host: smtp.gmail.com
    username: sovcomtrade6@gmail.com
    password: hlazehwmerlmyjwd
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: debug
      hibernate:
        sql: debug
    web: debug

application:
  jwt:
    key: ${JWT_SECRET_KEY}
  api:
    version: v1
  base-path: "/api/${application.api.version}"
  cb:
    xml-base-url: "http://www.cbr.ru/scripts"
    json-base-url: "https://www.cbr-xml-daily.ru"
  invest-com:
    base-url: "https://ru.investing.com"